name: Bug Report
description: "Something is not working as expected"
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: observed
    attributes:
      label: Observed behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: input
    id: studio_version
    attributes:
      label: UiPath Studio version
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
  - type: textarea
    id: notes
    attributes:
      label: Additional context
